name = "paimon-plus"
pages_build_output_dir = "./dist"
compatibility_date = "2024-07-14"

[[ kv_namespaces ]]
binding = "kv"
id = "45c070da16fc4324a71bbc6b390c4235"
preview_id = "genshin-cache"

[[ d1_databases ]]
binding = "showcase"
database_name = "genshin-showcase"
database_id = "f3603251-bb65-4a83-9314-53fd72c78b5a"

[[ d1_databases ]]
binding = "statistical"
database_name = "genshin-statistical-sources"
database_id = "ecd6e443-de93-48b2-8d30-038e2613bf95"

[ limits ]
cpu_ms = 100
